const supervisors = [
    { id: 'a29455',
    email: 'augustinemmerole@gmail.com',
    first_name: 'augustine',
    last_name: 'mmerole',
    password: 'augmme', 
    job_role: 'supervisor',
  },
    { id: 'a28264',
    email: 'harryoshilim@gmail.com',
    first_name: 'harryson',
    last_name: 'oshilim',
    password: 'harosh',
    job_role: 'supervisor',
  },
  { id: 'a31798',
  email: 'pascalpee2022@gmail.com',
  first_name: 'pascal',
  last_name: 'peters',
  password: 'paspet',
  job_role: 'supervisor',
},
  { id: 'a29122',
  email: 'obasohan@gmail.com',
  first_name: 'Stephen',
  last_name: 'Obasohan',
  password: 'stephoba',
  job_role: 'super admin,'
},
  ];
  
  export default supervisors;